export { default as LoginPage } from "./LoginPage";
export { default as RegistrationPage } from "./RegistrationPage";
export { default as BoardPage } from "./BoardPage";
export { default as ContributionPage } from "./ContributionPage";
export { default as GamesPage } from "./GamesPage";
export { default as HomePage } from "./HomePage";
export { default as PlatformsPage } from "./PlatformsPage";
export { default as PollsPage } from "./PollsPage";
export { default as UserAccountPage } from "./UserAccountPage";
